### ISSUE TITLE
question: how to save report results to a file

### ISSUE THREAD

**Issue by bboydflo** [DevExpress/testcafe-reporter-list#2]
is it possible to save the report in a file? how can I do that from the command line? 
I have tried `--report-path testcafe-report.txt` and `-rp testcafe-report.txt` but none of them work :(

**Comment by AlexanderMoskovkin** [comment]
Hi @bboydflo,

If you need to save the report to an external file, you can redirect the command output stream to the file by using the > redirection operator and specifying the report file path.

```sh
testcafe all tests/sample-fixture.js > tests/test-results.txt
```

**Comment by bboydflo** [comment]
thanks so much

**Comment by AlexanderMoskovkin** [comment]
You are always welcome.

FYI: starting with the `testcafe@0.18.0` version (it's not released yet) you can optionally use another syntax:
`testcafe chrome test.js -r list:test-results.txt`
It's implemented in https://github.com/DevExpress/testcafe/pull/1622

**Comment by bboydflo** [comment]
@AlexanderMoskovkin I've actually looked into issues and then tests and tried that syntax as well. I am looking forward for the `testcafe@0.18.0` release
